version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chiki-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ChikiAPIDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chiki-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user_admin:password123@db:5432/ChikiAPIDB?schema=public
      - PORT=3000
      - JWT_SECRET=tu_clave_secreta_super_segura
    volumes:
      - .:/app             
      - /app/node_modules   
      - ./uploads:/app/uploads
    command: sh -c "npx prisma migrate dev && npm run dev"

volumes:
  postgres_data: